### PR TITLE
Fix BUG: Duplicated ID happen on MS SQL Server If run multiple JVM instance.

### PR DESCRIPTION
**Pull request by amanraj2520**
Copied from https://github.com/datanucleus/datanucleus-rdbms/pull/354

use with (updlock) to support MS SQL Server.

### CODE REVIEW

**Comment by amanraj2520** [comment]
@andyjefferson Can you please review and approve this

**Comment by andyjefferson** [comment]
Why is there supportedOptions.add(LOCK_WITH_SELECT_FOR_UPDATE); in SQLServerAdapter when that RDBMS doesn't support FOR UPDATE ? (and where is this LOCK_WITH_SELECT_FOR_UPDATE defined? ... the variable had ROW_ added some versions ago)
What is generateLockWithSelectForUpdate(...) when it is seemingly not called?
Why isn't there simply a method on DatastoreAdapter (SQLServerAdapter) that returns "(UPDLOCK)" if that is the WITH option needed somewhere? 
In SequenceTable why is all of this code finding wherePos, when you know wherePos from several lines before when it is added?

**Comment by andyjefferson** [comment]
No reply.

**Define WHAT you are trying to achieve.** 
SequenceTable (aka value-generator=increment) will currently create SQL like this

SELECT {myColumn} FROM {myTable} WITH (UPDLOCK,ROWLOCK) WHERE {col}=?";

for SQLServer. Define what is incorrect about that. It is consistent with what is generated for a normal SELECT statement for that datastore. i.e the SQL generated by SequenceTable should be the same as that generated by SelectStatement. 

Otherwise I'll close this

**Comment by amanraj2520** [comment]
@andyjefferson There was some emergency at my end, so I was out for a couple of weeks. I have raised a fresh PR - https://github.com/datanucleus/datanucleus-rdbms/pull/472. Sincere apologies for the delay. Made the relevant changes

**Pull request closed without merging**
