### PR TITLE
Duplicated ID happen on MS SQL Server If run multiple JVM instance.

### PR DESCRIPTION
**Pull request by amanraj2520**
The original PR - https://github.com/datanucleus/datanucleus-rdbms/pull/354/files

use with (updlock) to support MS SQL Server.

### CODE REVIEW

**Comment by amanraj2520** [comment]
@andyjefferson Can you please review this.

**Comment by andyjefferson** [comment]
You seem to want to use "WITH (UPDLOCK)" on the SequenceTable SELECT, yet use "WITH(UPDLOCK,ROWLOCK)" on the SelectStatement. That would be totally inconsistent.

**Comment by amanraj2520** [comment]
@andyjefferson Are you suggesting to use WITH(UPDLOCK,ROWLOCK) instead of WITH (UPDLOCK)?

**Comment by andyjefferson** [comment]
I'm not suggesting anything. As I've said before SequenceTable (aka value-generator=increment) will currently create SQL like this
SELECT {myColumn} FROM {myTable} WITH (UPDLOCK,ROWLOCK) WHERE {col}=?";
for SQLServer. Define what is incorrect about that. This is consistent with what is generated for a normal SELECT statement for that datastore. i.e the SQL generated by SequenceTable should be the same as that generated by SelectStatement.

Your "proposal" would make SequenceTable create SQL like
SELECT {myColumn} FROM {myTable} WITH (UPDLOCK) WHERE {col}=?";
whilst SelectStatement would still create using "WITH (UPDLOCK,ROWLOCK) ". i.e utterly inconsistent

**Comment by amanraj2520** [comment]
@andyjefferson SELECT {myColumn} FROM {myTable} WITH (UPDLOCK,ROWLOCK) WHERE {col}=?"; In which release of datanucleus is this change consumed in? In 5.2.2?

Let me elaborate the reason why I am doing it this way. I am not exactly sure of how things work end to end in datanucleus, so please pardon me. In HIVE we are using datanucleus-rdbms as 5.2.2. https://issues.apache.org/jira/browse/HIVE-23866 As mentioned in this ticket, we are getting an exception as Cannot insert duplicate key in object 'dbo.TBL_COL_PRIVS'. The duplicate key value is (241408091).

If I patch this change to datanucleus 5.2.2 jar and replace the jars, this exception is resolved. This original PR https://github.com/datanucleus/datanucleus-rdbms/pull/354/files addressed the same issue in Hive. If possible can you please suggest any other fix that I should explore or changes in this PR I should make or shed light in possibly why this issue is coming in the first place?

**Comment by amanraj2520** [comment]
@andyjefferson Please suggest some steps to fix this

**Comment by andyjefferson** [comment]
As said from the outset, consistency is what is needed between different statements. Basic Select has "WITH (UPDLOCK,ROWLOCK)" and you say SequenceTable needs "WITH (UPDLOCK)". 

So 
1. look at the difference between those and understand why "WITH (UPDLOCK)" is needed, and 
2. use just "WITH (UPDLOCK)" for both statements (i.e simply change https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/SQLServerAdapter.java#L501 to "(UPDLOCK)". Make sure that then works with all cases.

We do not have SQLServer so cannot check that, so if this is changed and someone reports a problem it will be changed back

**Comment by amanraj2520** [comment]
@andyjefferson This makes sense. I see that WITH (ROWLOCK, UPDLOCK) was committed in 5.2.5 release for rdbms. Currently in our hive, we are using 5.2.2, that's why I think this patch was needed. I am testing it with 5.2.5 release once. Since in 5.2.5 we have made SqlAdapter's select in sync with SequenceTable. Will let you know

**Comment by andyjefferson** [comment]
See https://github.com/apache/hive/pull/3148

**Comment by amanraj2520** [comment]
Yes @andyjefferson you are correct. This fix was present in datanucleus rdbms >= 5.2.5. I have done this change in Hive and testing scenarios. As it is I completely agree with the inconsistent behavior of (UPDLOCK) (SequenceTable) and (UPDLOCK, ROWLOCK) (Normal Select) after this PR. We should close this with the conclusion that if anyone is facing the Duplicate ID issue, they can just migrate to datanucleus rdbms >=5.2.5.

Thanks a lot Andy for making this crystal clear.

**Comment by amanraj2520** [comment]
We can close this if you want.

**Comment by andyjefferson** [comment]
Thx for clarifying the situation

**Pull request closed without merging**
