### PR TITLE
Datanucleus rdbms 5.2.7 application identity

### PR DESCRIPTION
**Pull request by meysam**
Based on Oracle Doc, "The getGeneratedKeys() method enables you to retrieve the auto-generated key fields. The auto-generated keys are returned as a ResultSet object.

If key columns are not explicitly indicated, then Oracle JDBC drivers cannot identify which columns need to be retrieved. When a column name or column index array is used, Oracle JDBC drivers can identify which columns contain auto-generated keys that you want to retrieve. However, when the Statement.RETURN_GENERATED_KEYS integer flag is used; Oracle JDBC drivers cannot identify these columns. When the integer flag is used to indicate that auto-generated keys are to be returned, the ROWID pseudo column is returned as a key. The ROWID can be then fetched from the ResultSet object and can be used to retrieved other columns."

Adding a bit changes to support this issue when using application-identity in Oracle JDBC

### CODE REVIEW

**Comment by meysam** [comment]
@andyjefferson as you mentioned in other [PR](https://github.com/datanucleus/datanucleus-rdbms/pull/372) I've changed the code but I see this PR has failed. do you have other rules or comments?

**Comment by TakahikoKawasaki** [comment]
Hello @andyjefferson, Nice to meet you. I'm Taka, co-founder of [Authlete, Inc.](https://www.authlete.com/)

The build log says as follows:

> [ERROR] Failed to execute goal on project datanucleus-rdbms: Could not resolve dependencies for project org.datanucleus:datanucleus-rdbms:jar:6.0.0-m1-SNAPSHOT: Failed to collect dependencies at org.datanucleus:datanucleus-core:jar:[5.9,6.9): No versions available for org.datanucleus:datanucleus-core:jar:[5.9,6.9) within specified range -> [Help 1]

It seems that the build system tried to use `datanucleus-rdbms:jar:6.0.0-m1-SNAPSHOT` but the dependency was not available. Is the build system by any chance misconfigured? Could you help us to solve the problem?

**Comment by andyjefferson** [comment]
Build system is correctly set up. Github master is for v6. If you want some earlier version you use the correct branch for that. If you use v6 then you need to download and build v6 plugins

**Comment by TakahikoKawasaki** [comment]
Ah, understood. Thank you. The PR should be created against v5 branch, not against the master (v6).

**Comment by meysam** [comment]
@andyjefferson do you have any plan to release v6?

**Pull request closed without merging**
