### PR TITLE
Bugfix: wrong query generated on interface column

### PR DESCRIPTION
**Pull request by dcheung2**
Given
```
interface I{...}
interface I2{...}
class Other implements I {...}
class Base implements I {...}
class Mid extends Base implementds I2 {...}
class Impl extends Mid {...}

class Target{
 I col;
 I2 col2;
}
```

When
a)
  filter = "this.col = val"
  parameter = "Impl val"
  execute JDO query with a Impl(key=123) as the parameter
b)
  filter = "this.col = val"
  parameter = "Base val"
  execute JDO query with a Base(key=456) as the parameter

Then
Expected SQL
`SELECT ... FROM TARGET WHERE TARGET.COL_BASE_EID = 123`
`SELECT ... FROM TARGET WHERE TARGET.COL_BASE_EID = 456`

Actual SQL
for query a)
`SELECT ... FROM TARGET WHERE TARGET.COL_BASE_EID = 123`
for query b) incorrectly generated
`SELECT ... FROM TARGET WHERE TARGET.COL_OTHER_EID = 456 AND TARGET.COL_BASE_EID = null`

This patch should correct the the above SQL when filter on `col`.

But the case of `col2` is not addressed yet.

### CODE REVIEW

**Comment by andyjefferson** [comment]
Please can you provide an outline test with those classes (and metadata), and test class that shows this situation. I don't have the time to code up something that has an incomplete definition just to test/understand it. Thx

**Comment by dcheung2** [comment]
```
<jdo>
  <package name="test.target">
    <class name="Target">
        <field name="key" value-strategy="increment" primary-key="true" />
        <field name="col">
          <extension vendor-name="datanucleus" key="implementation-classes" value="test.other.Other, test.foo.Base, test.bar.SomethingElse" />
        </field>
        <field name="col2">
          <extension vendor-name="datanucleus" key="implementation-classes" value="test.foo.Mid, test.bar.SomethingElse" />
        </field>
     </class>
  </package>
  <package name="test.foo">
        <class name="Base">
            <inheritance strategy="new-table" >
                <discriminator strategy="value-map" value="BASE" />
            </inheritance>
           <field name="key" value-strategy="increment" primary-key="true" />
     </class>
      <class name="Mid">
            <inheritance strategy="superclass-table" >
                <discriminator strategy="value-map" value="MID" />
            </inheritance>
     </class>
      <class name="Impl">
            <inheritance strategy="superclass-table" >
                <discriminator strategy="value-map" value="IMPL" />
            </inheritance>
     </class>
   </package>
  <package name="test.other">
        <class name="Other">
           <field name="key" value-strategy="increment" primary-key="true" />
     </class>
   </package>
  <package name="test.bar">
        <class name="SomethingElse">
           <field name="key" value-strategy="increment" primary-key="true" />
     </class>
   </package>
</jdo>
```

**Comment by andyjefferson** [comment]
FYI, a simple test is defined by https://www.datanucleus.org/documentation/problem_reporting.html#jdo
**or better still** include one in the DN test suite (so then any feature you are supporting is checked before any release and so doesnt break in the future) ... https://github.com/datanucleus/tests/blob/master/jdo/identity/src/test/org/datanucleus/tests/InterfacesTest.java

**Comment by dcheung2** [comment]
Not sure how could I do a MVCE here.

But the problem I see from code is that `ExpressionUtils.getEqualityExpressionForObjectExpressions` confused between three `implementation-classes` with another case of one implementation class with three FK-columns. 
(around line 367 if I remember it correctly)

This patch mitigate it by using base class to match for a simple `eq`  in `ObjectExpression.processComparisonOfImplementationWithReference`  and avoid using `getEqualityExpressionForObjectExpressions` at all if possible.

**Comment by andyjefferson** [comment]
A test demonstrates something that words do not. Whether it is possible to create a valid Assert or not is separate to the issue. Other people need to be able to see it to fully understand it.

**Comment by dcheung2** [comment]
Thanks, let me take a look

**Comment by andyjefferson** [comment]
My guess of your "test case" is attached. [rdbms-392.zip](https://github.com/datanucleus/datanucleus-rdbms/files/6885640/rdbms-392.zip).
Kindly confirm this is the case. Also the method had a line "// TODO Handle case where we have a subclass of the implementation here". I presume this is what you are fixing. If so then that line can be removed.

**Comment by dcheung2** [comment]
Yes. It is the case it is fixing.

I am not sure if my patch actually fixing it or just hide it.
The datanucleus code require a good understanding of the internal API, and I am guessing quite a lot in Expression.
The patch works for me though.

**Pull request merged**
