### PR TITLE
Fix BUG: Duplicated ID happen on MS SQL Server If run multiple JVM instance. #353

### PR DESCRIPTION
**Pull request by wenjunma004**
use with (updlock) to support MS SQL Server.

### CODE REVIEW

**Comment by andyjefferson** [comment]
Firstly thanks for trying to fix your issue; we don't have that database so are dependent on contributions.

Secondly, you seem to be reusing the option "SELECT ... FOR UPDATE" for something that is NOT "SELECT ... FOR UPDATE" when used by SQL Server. Also that option is used by SelectStatement, adding on "FOR UPDATE" ... does that work for SQLServer like that? 

IMHO It would be better to introduce a different option for what SQL Server requires (since it is distinct to what "SELECT FOR UPDATE" is for these other datastores) and reference that option in SelectStatement and SequenceTable

**Comment by wenjunma004** [comment]
Hi andyjefferson,
I use this one for sql server 

  public String generateLockWithSelectForUpdate(String statement)



    {



        String modifier = " with (updlock)";



        int wherePos = statement.toUpperCase().indexOf(" WHERE ");



        if (wherePos < 0) {



            return statement + modifier;



        }



        return statement.substring(0, wherePos) + modifier +



                statement.substring(wherePos, statement.length());



    }



} 

I have applied this change and test on our SQL it works fine.

**Comment by andyjefferson** [comment]
That has nothing to do with my comments. I can see what your PR does. 

You have decided to add the option LOCK_WITH_SELECT_FOR_UPDATE to SQL server, but SQL Server does not support "SELECT ... FOR UPDATE" (as you said). Hence you are overriding an option for something it is NOT intended for. Also, you have NOT updated SelectStatement to use this "updlock" and so it would get "FOR UPDATE" appended.

You need to rewrite your PR to either
1. add a new option something like LOCK_WITH_SELECT_WITH_UPDLOCK, and update SelectStatement / SequenceTable to use that

or 
2. Rename the option LOCK_WITH_SELECT_FOR_UPDATE to be something like LOCK_WITH_SELECT_PLUS_PREFIX and then make use of that in SelectStatement / SequenceTable.

**Comment by andyjefferson** [comment]
While doing that, also consider the option LOCK_OPTION_PLACED_AFTER_FROM and LOCK_OPTION_PLACED_WITHIN_JOIN which puts
`WITH (UPDLOCK,ROWLOCK)`
after a FROM. SQLServer is already marked as using that. What option is in use for a particular datastore should be logical and understandable

**Comment by wenjunma004** [comment]
Hi andyjefferson,

I add LOCK_WITH_SELECT_WITH_UPDLOCK and update SequenceTable to fix this problem. Please review it. 

Thanks
Wenjun Ma

**Comment by andyjefferson** [comment]
Presumably your code now means that SequenceTable (i.e value generation) will lock using "WITH (UPDLOCK)" and a normal SELECT (i.e SelectStatement) will lock using "WITH (UPDLOCK, ROWLOCK)" ... yes? So why are these situations doing different things?

**Comment by wenjunma004** [comment]
Hi andyjefferson,

I following your suggestion

"add a new option something like LOCK_WITH_SELECT_WITH_UPDLOCK, and update SelectStatement / SequenceTable to use that"

Thanks
Wenjun Ma

**Comment by andyjefferson** [comment]
And as I said, your code has different treatment of SELECT statement locking between SelectStatement and SequenceTable. They should be consistent. As I also said, the current way of locking with SQLServer was to add "WITH (UPDLOCK, ROWLOCK)" after the FROM clause (due to option LOCK_OPTION_PLACED_AFTER_FROM). Unfortunately this had not been added to SequenceTable. You now update SequenceTable with "WITH (UPDLOCK)" only, and with yet a different option. WHY CAN YOU NOT JUST USE THE SAME OPTION AS ALREADY EXISTS? (I added code for this in to DataNucleus master).

**Comment by wenjunma004** [comment]
If we upgrade to latest version any thing we need change? 
currently we use those versions 
    <datanucleus-api-jdo.version>4.2.4</datanucleus-api-jdo.version>
    <datanucleus-core.version>4.1.17</datanucleus-core.version>
    <datanucleus-jdo.version>3.2.0-m3</datanucleus-jdo.version>
    <datanucleus-rdbms.version>4.1.19</datanucleus-rdbms.version>
we define OR mapping with this:
https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/main/resources/package.jdo

**Comment by andyjefferson** [comment]
I assume from your comment that current datanucleus-rdbms MASTER branch fixes your issue. If YES, then please close this pull request.


About 4.1.x, well I won't be putting any change into DN GitHub for 4.1.x (since it is retired a long time ago, and I no longer have a JDK to develop it with) BUT you can fork it and use your own version. To apply the same change as I made


MASTER has
https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/valuegenerator/SequenceTable.java#L112

and 4.1.20 has this
https://github.com/datanucleus/datanucleus-rdbms/blob/datanucleus-rdbms-4.1.20/src/main/java/org/datanucleus/store/rdbms/valuegenerator/SequenceTable.java#L112

so replace line 112 in v4.1.20 with these lines
```
fetchStmt = "SELECT " + colNextVal.getIdentifier() + " FROM " + identifier.getFullyQualifiedName(false);
        if (dba.supportsOption(DatastoreAdapter.LOCK_OPTION_PLACED_AFTER_FROM))
        {
            fetchStmt += " WITH " + dba.getSelectWithLockOption();
        }
        fetchStmt += " WHERE " + colSequenceName.getIdentifier() + "=?";
```


If instead you upgrade to 5.2.x you would need to follow [this guide](https://www.datanucleus.org/products/accessplatform_5_2/migration.html), and work your way through from v4.1.x. In general the things that need changing would be persistence properties NOT mapping.

**Comment by wenjunma004** [comment]
Hi andyjefferson,

I will close it.  We will use local build v4.1.20 version 

Thanks
Wenjun Ma

**Pull request closed without merging**
